@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODE5MzViMjI1NWZlZDQxMmE2N2JhMjYiLCJ1c2VybmFtZSI6InJlbGlnaW9uIiwiaWF0IjoxNzQ2NDgyNjEwfQ.YKA9YmbUbUt2n-cCmmsIELm4ZpYdbeJD6h-DAtEoIqc

### Create a new event
POST {{host}}/api/events
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "recurring every week but altered",
  "startTime": "2025-05-10T12:00:00.000Z",
  "endTime": "2025-05-10T13:00:00.000Z",
  "isAllDay": false,
  "location": "Tromsø",
  "description": "Recurring weekly but og on sat and others on mon",
  "recurrence": {
    "frequency": "weekly",
    "frequencyInterval": 1,
    "weekly.daysOfWeek": [
      1
    ],
    "endless": false,
    "untilNumber": "4"
  }
}

### Get all events
GET http://localhost:3000/api/events
Authorization: Bearer {{ token }}

### Delete an event
DELETE http://localhost:3000/api/events/68193806255fed412a67ba67
Authorization: Bearer {{ token }}


### Create a new task
POST http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "title": "Boomeh",
  "description": "literally so annoying",
  "dueDate": "2025-04-24T22:34:00.000Z",
  "priority": 3
}

{
  "title": "Boomeh",
  "description": "literally so annoying",
  "dueDate": "2025-04-24T22:34:00.000Z",
  "priority": 3
}

### Get combined calendar items
GET http://localhost:3000/api/calendar
Authorization: Bearer {{ token }}

### Get expanded events
GET http://localhost:3000/api/events/expanded?start=2025-04-01&end=2025-08-28
Authorization: Bearer {{ token }}
