@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFiZTQ3MzlkYzY0ZTM3NmZlMTAwNGEiLCJ1c2VybmFtZSI6ImthYm9vbSIsImlhdCI6MTc0NjY1ODQxOX0.fr3RyNCHmzB5koZBbA-h9OYCaY4C8s8pa2gQT_w2rcs

### Create a new event
POST {{host}}/api/events
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "medium",
  "startTime": "2025-06-10T12:00:00.000Z",
  "endTime": "2025-06-10T13:00:00.000Z",
  "isAllDay": false,
  "location": "Alta, Norway",
  "description": "just a medium event",
  "recurrence": {
    "frequency": "daily",
    "frequencyInterval": 1,
    "endless": false,
    "untilNumber": 19
  }
}

### Get all events (recurring counts as the OG only)
GET http://localhost:3000/api/events
Authorization: Bearer {{ token }}

### Delete an event
DELETE http://localhost:3000/api/events/681cc4dd8b0c638cdf09527e
Authorization: Bearer {{ token }}


### Create a new task
POST http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "title": "Boomeh",
  "description": "literally so annoying",
  "dueDate": "2025-04-24T22:34:00.000Z",
  "priority": 3
}

{
  "title": "Boomeh",
  "description": "literally so annoying",
  "dueDate": "2025-04-24T22:34:00.000Z",
  "priority": 3
}

### Get combined calendar items
GET http://localhost:3000/api/calendar
Authorization: Bearer {{ token }}

### Get expanded events
GET http://localhost:3000/api/events/expanded?start=2025-06-22&end=2028-12-28
Authorization: Bearer {{ token }}
