@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODQxYTcwOTRlNzNlZjQzYTliNWRkMWIiLCJ1c2VybmFtZSI6ImNhbWRlbm5qIiwiaWF0IjoxNzQ5MTM0Njc0fQ.9OWuT1f7KISnD_AtL5IanEIwi6yBjciL3VTu8JrPcjA

### Create a new study plan
POST {{host}}/api/study-plan/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "My Study Plan",
  "description": "A plan to study programming languages",
  "date": "2025-10-01",
  "focusTime": 120,
  "breakTime": 60,
  "cycles": 3,
  "dragToNextDay": false
}

### Get all user study plans
GET {{host}}/api/study-plan/
Authorization: Bearer {{token}}

### Delete study plan
DELETE {{host}}/api/study-plan/6841a1b73b6a6007223cab6e
Authorization: Bearer {{token}}