POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "b",
    "email": "b@b.com",
    "password": "b"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "qp",
    "password": "qp"
}

###
GET http://localhost:3000/api/auth/user/67fa6b3ca8752d239109984d

###
GET http://localhost:3000/api/auth/all

###
PATCH http://localhost:3000/api/auth/update/67fa6b3ca8752d239109984d
Content-Type: application/json

{
    "username": "johnpork"
}

###
DELETE http://localhost:3000/api/auth/delete/67fa6b3ca8752d239109984d