POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "a",
    "email": "a@a.com",
    "password": "a"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "jow",
    "password": "jow"
}

###
GET http://localhost:3000/api/auth/user/67f92f0f840c1b13b816e879

###
GET http://localhost:3000/api/auth/all

###
PATCH http://localhost:3000/api/auth/update/67f92f0f840c1b13b816e879
Content-Type: application/json

{
    "password": "jow"
}